name: ci

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      
      -
        name: Build and push
        run: |
          # Obtener la etiqueta en minúsculas
          TAG=$(echo "${{ github.event_name }}-${{ github.sha }}" | tr '[:upper:]' '[:lower:]')

          # Construir y subir la imagen con la etiqueta en minúsculas
          docker buildx build --tag "${{ secrets.DOCKER_USERNAME }}/${{ github.event.repository.name }}:${TAG}" --push .
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
